#!/bin/bash

set -e
set -o pipefail
set -x

function user_exists () {
  psql -c "SELECT usename FROM pg_catalog.pg_user WHERE usename = 'univsystem'" -d postgres |
  grep "(1 row)"
}

function create_user () {
  psql -c "CREATE USER univsystem PASSWORD 'univsystem' LOGIN" -d postgres
}

user_exists || create_user

psql -c "DROP DATABASE IF EXISTS $1" -d postgres
psql -c "CREATE DATABASE $1" -d postgres
